name: Build ClickOnce

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - "!main"

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions:
  contents: write

jobs:
  setup:
    runs-on: windows-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ClickOnce installer available: https://alleey.github.io/PreventScreenLock/
        draft: true
        prerelease: false

  build:
    runs-on: windows-latest
    needs: [setup]
    steps:
    - name: Checkout repository
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for tags

    - name: Read meta data
      id: metadata
      uses: actions/github-script@v6
      with:
        script: |
          const { execSync } = require('child_process');
          let latestTag;
          try {
            latestTag = execSync('git describe --abbrev=0 --tags').toString().trim();
          } catch (error) {
            console.log('No tags found, using default version 0.0.0.1');
            console.log(error);
            latestTag = 'v0.0.0.1';
          }
          const version = latestTag.startsWith('v') ? latestTag.substring(1) : latestTag;
          console.log(`Tag:${latestTag} -> Version:${version}`);
          core.setOutput('value', version)

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Publish
      shell: pwsh
      run: ./publish/publish.ps1 -version "${{ steps.metadata.outputs.value }}"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./clickonce

    - name: Release Artifacts
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.setup.outputs.upload_url }}
        asset_path: clickonce/
        asset_name: preventscreenlock-${{ steps.metadata.outputs.value }}.zip
        asset_content_type: application/zip